### ISSUE TITLE
Bug with enchantments on 1.8.3

### ISSUE THREAD

**Issue by BorlCand** [Shevchik/ProtocolSupport#10]
Compiled from source code with your last commit on March 8 to start Spigot 1.8.3 server. All working fine, BUT big bug is in enchantments. It reverts back to 1.7 version (without lapis and taking many levels) with every client. /ps list command can't identify which version every player uses. I can't understand one more thing: server on Linux-based machine with only ProtocolSupport plugin uses 1.7 enchantments, but when I download this server on Windows-based machine it works like a charm, with 1.8 enchantments.

I can provide access, logs, screenshots and other needed information and help to fix this issue.

P.S. Server uses BungeeCord proxy.

**Comment by Shevchik** [comment]
1.8.3 added epoll connection (It is available only on linux and it is faster than NIO). But it is somewhat unstable when it comes to channel connected/disconneted state. Will have to find a forkaroud for that.
You may temporally disable epoll by setting use-native-transport to falste in server properties.
That bug is also the reason why i don't release new version yet.

**Comment by BorlCand** [comment]
Sorry, but it didn't helped. Changed use-native-transport to false. 

OS: CentOS 7
Arch: x86_64
Server: Spigot 1.8.3 rev 363
Bungeecord: old 1.8-SNAPSHOT version
Java: OpenJDK 1.7.0_75:
java version "1.7.0_75"
OpenJDK Runtime Environment (rhel-2.5.4.2.el7_0-x86_64 u75-b13)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)

**Comment by Shevchik** [comment]
Forgot that you are using bungeecord. Try without it first.

**Comment by BorlCand** [comment]
Didn't helped

**Comment by Shevchik** [comment]
Can i have a server log?

**Comment by Shevchik** [comment]
Still unable to reproduce
